import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { StyleSheet, Text, TextInput, View } from "react-native";
import { createAppointment, getAvailability } from "@/api/appointments";
import { getApiErrorMessage } from "@/api/errors";
import { AppButton, AppCard, AppScreen, colors, EmptyState, ErrorState, FieldError, LoadingState, SectionHeader, uiStyles } from "@/components/ui";

export default function BookAppointmentScreen() {
  const client = useQueryClient();
  const [date, setDate] = useState("");
  const [duration, setDuration] = useState(30);
  const [selected, setSelected] = useState<{ dentist: number; start: string } | null>(null);
  const [reason, setReason] = useState("");
  const [dateError, setDateError] = useState<string | undefined>();
  const [success, setSuccess] = useState(false);
  const availability = useQuery({ queryKey: ["availability", date, duration], queryFn: () => getAvailability({ date, duracionMin: duration }), enabled: /^\d{4}-\d{2}-\d{2}$/.test(date) });
  const create = useMutation({ mutationFn: () => createAppointment({ idOdontologo: selected!.dentist, fechaHora: selected!.start, duracionMin: duration, motivo: reason }), onSuccess: () => { client.invalidateQueries({ queryKey: ["appointments"] }); setSuccess(true); setSelected(null); } });
  function changeDate(value: string) { setDate(value); setSelected(null); setSuccess(false); setDateError(value && !/^\d{4}-\d{2}-\d{2}$/.test(value) ? "Usá el formato AAAA-MM-DD." : undefined); }
  if (success) return <AppScreen><AppCard variant="highlight"><Text style={styles.successTitle}>Solicitud enviada correctamente</Text><Text style={styles.successText}>La clínica revisará tu solicitud y te notificará cuando sea confirmada.</Text><AppButton title="Ver mis citas" onPress={() => router.replace("/(app)/appointments")} /><AppButton title="Solicitar otra cita" variant="secondary" onPress={() => setSuccess(false)} /></AppCard></AppScreen>;
  return <AppScreen><SectionHeader title="Solicitar cita" description="Elegí una fecha, un horario y contanos el motivo de tu consulta." /><AppCard><Text style={uiStyles.label}>1. Fecha</Text><TextInput placeholder="AAAA-MM-DD" keyboardType="numbers-and-punctuation" value={date} onChangeText={changeDate} style={[uiStyles.input, dateError && uiStyles.inputInvalid]} /><FieldError message={dateError} /></AppCard><AppCard><Text style={uiStyles.label}>2. Duración</Text><View style={styles.options}>{[30, 45, 60].map((value) => <AppButton key={value} title={`${value} min`} variant={duration === value ? "primary" : "secondary"} onPress={() => { setDuration(value); setSelected(null); }} />)}</View></AppCard>{availability.isLoading && <LoadingState label="Buscando horarios disponibles..." />}{availability.isError && <ErrorState message={getApiErrorMessage(availability.error, "No pudimos consultar la disponibilidad.")} onRetry={() => availability.refetch()} />}{availability.data && <AppCard><Text style={uiStyles.label}>3. Horario disponible</Text>{availability.data.dentists.length ? availability.data.dentists.map((dentist) => <View key={dentist.id} style={styles.dentist}><Text style={styles.dentistName}>{dentist.name}</Text><View style={styles.slots}>{dentist.slots.map((slot) => <AppButton key={slot.start} title={`${slot.start.slice(11, 16)} - ${slot.end.slice(11, 16)}`} variant={selected?.start === slot.start ? "primary" : "secondary"} onPress={() => setSelected({ dentist: dentist.id, start: slot.start })} />)}</View></View>) : <EmptyState title="No hay horarios disponibles" description="Probá con otra fecha o duración." />}</AppCard>}{selected && <AppCard><Text style={uiStyles.label}>4. Motivo de la consulta</Text><TextInput placeholder="Consulta, limpieza, control..." maxLength={150} value={reason} onChangeText={setReason} multiline style={[uiStyles.input, uiStyles.multiline]} /><Text style={styles.counter}>{reason.length}/150</Text><Text style={styles.confirmation}>Horario seleccionado: {new Date(selected.start).toLocaleString("es-SV", { dateStyle: "medium", timeStyle: "short" })}</Text><AppButton title="Enviar solicitud" loading={create.isPending} onPress={() => create.mutate()} />{create.isError && <Text style={styles.error}>{getApiErrorMessage(create.error, "No pudimos enviar la solicitud.")}</Text>}</AppCard>}</AppScreen>;
}

const styles = StyleSheet.create({ options: { gap: 10 }, dentist: { gap: 10, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, marginTop: 4 }, dentistName: { color: colors.navy, fontWeight: "700" }, slots: { gap: 8 }, counter: { color: colors.muted, textAlign: "right", fontSize: 12 }, confirmation: { color: colors.info, lineHeight: 20 }, successTitle: { color: colors.success, fontSize: 20, fontWeight: "800" }, successText: { color: colors.muted, lineHeight: 21 }, error: { color: colors.danger, marginTop: 8 } });
